b=str(input("Enter a string:"))
print("python script to demonstrate string methonds")
print("To capitalize the first character",b.capitalize())
print("To casefold the character",b.casefold())
print("To center the string",b.center(20,"*"))
print("To count the character 'a' in the string",b.count('a'))
print("To encode to binary",b.encode())
print("To check the string endswith *",b.endswith("*"))
print("To find starting position of substring",b.find("abc"))
print("To get starting index of character 'c'",b.index("c"))
print("To check the string is numeric",b.isnumeric())
print("To check the string is alphabet",b.isalpha())
print("To check the string is lower",b.islower())
print("To split the string",b.split())
